require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VisitorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Visitor. As you add validations to Visitor, be sure to
  # adjust the attributes here as well.
  let(:existing_visitor) {
    FactoryGirl.create(:visitor)
  }

  let(:valid_attributes) {
    FactoryGirl.build(:visitor).attributes
  }

  let(:invalid_attributes) {
    { email: '' }
  }

  describe "GET #new" do
    context "with valid params" do
      it "assigns the requested visitor as @visitor" do
        get :new
        expect(assigns(:visitor)).to be_a(Visitor)
      end
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Visitor" do
        expect {
          post :create, {visitor: valid_attributes}
        }.to change(Visitor, :count).by(1)
      end

      it "assigns a newly created visitor as @visitor" do
        post :create, {visitor: valid_attributes}
        expect(assigns(:visitor)).to be_a(Visitor)
        expect(assigns(:visitor)).to be_persisted
      end

      it "redirects to the created visitor" do
        post :create, {visitor: valid_attributes}
        expect(response).to redirect_to(root_path)
      end
    end

    context "with invalid params" do
      it "returns the errors in the model" do
        post :create, {format: :json, visitor: invalid_attributes}

        test_visitor = Visitor.new(invalid_attributes)
        test_visitor.valid?

        expect(response.body).to eq(test_visitor.to_json)
      end
    end
  end
end
